// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/api/search.ts";
import * as $2 from "./routes/blog/first.tsx";
import * as $3 from "./routes/blog/index.tsx";
import * as $4 from "./routes/index.tsx";
import * as $$0 from "./islands/SearchBar.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/api/search.ts": $1,
    "./routes/blog/first.tsx": $2,
    "./routes/blog/index.tsx": $3,
    "./routes/index.tsx": $4,
  },
  islands: {
    "./islands/SearchBar.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
